import = [
  "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0

decorations = "None"

opacity = 0.8

[font]
normal.family = "FiraCode Nerd Font"
